### ISSUE TITLE
Toadserver hangs on getfile/postfile

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/toadserver#33] opened 2016-02-11 10:42 UTC
Using 

    curl http://localhost:11113/getfile/hungryToad.txt
  
causes it to hang, see the logs:

```
Initializing toadserver...
Receiving GET request
Looking for filename:                         hungryToad.txt
Found corresponding hash:                     QmXwgzQ312fBA8Fco3kQiEppQzV3KStwHtidnguhCcmVHA
Getting it from IPFS...
Receiving GET request
Looking for filename:                         hungryToad.txt
Found corresponding hash:                     QmXwgzQ312fBA8Fco3kQiEppQzV3KStwHtidnguhCcmVHA
Getting it from IPFS...
```

I also tried a couple of times to reinit toadserver:

    eris services stop toadserver && eris services rm toadserver && \ 
    eris services start toadserver --chain=bob

It is possible though to retrieve using `gateway.ipfs.io` directly, and previously I was at least able to post files. 

It is able to post a file, but then hangs.

**Comment by kootenpv** [comment] 2016-02-11 10:50
Looking at chain bob's log does reveal some errors:

    ERROR     swarm2: swarm listener accept error: write tcp 127.0.0.2:4001->127.0.0.1:4001: write: broken pipe

**Comment by zramsay** [comment] 2016-02-12 01:51
Are you sure that error is from the chain logs (I ask because port 4001 is the ipfs p2p port). Can you dump the ipfs logs here (`eris services logs ipfs`)? We recently updated the ipfs image; that might be related. Sometimes ipfs is the cause of the hanging (for reasons unknown - [this blob](https://github.com/eris-ltd/toadserver/blob/master/test.sh#L112-L117) was added & gets the test passing). Can you run that test and see if it passes?

**Comment by kootenpv** [comment] 2016-02-12 08:18
eris services logs ipfs:

```
08:17:03.089 ERROR     swarm2: swarm listener accept error: EOF swarm_listen.go:129
08:17:53.078 ERROR core/serve: Path Resolve error: context canceled gateway_handler.go:500

```
@zramsay Perhaps you can try

    eris files get QmXwgzQ312fBA8Fco3kQiEppQzV3KStwHtidnguhCcmVHA testtest

That command hangs for me, using eris 0.11.1

**Comment by zramsay** [comment] 2016-02-12 17:15
Can confirm this behaviour. Will investigate further. One quirk that I've noticed is that if you `put` a file to ipfs, check that it's there through the gateway, then remove your ipfs node (location where file is actually being hosted)...the file may no longer be reliably gettable but might still appear on gateway. This isn't intended behaviour, however, I've come to the conclusion that you definitely want 2-3 ipfs nodes on which you've `eris files cache HASH` to ensure persistent access to the file. The `TOADSERVER_IPFS_NODES` of w/e the env var is, is meant to abstract away/simplify that process (of pinning your files to a handful of nodes). All this to say is that a hanging `get` can often be fixed with >1 ipfs nodes having the file.

**Comment by compleatang** [comment] 2016-02-14 09:01
There was an ipfs image build which was seemingly bad. It hung completely on me in cli tests. The current builds of the ipfs image have fixed that. Not sure if it is connected to this issue, but may have been.

**Comment by kootenpv** [comment] 2016-02-15 19:33
With 0.11.2 toadserver's `../getfile/...` now works.

`../postfile/..` does get further, but still hangs:
```

Receiving POST request
File to register:                             contract.sol
Sending File to eris' IPFS gateway
Hash received:                                Qmc1CiNDurQU6UQ9sUyuKbdFQvW2avpcCgnDTax5K1rfsy
Sending name registry transaction:
                                     filename=contract.sol
                                         hash=Qmc1CiNDurQU6UQ9sUyuKbdFQvW2avpcCgnDTax5K1rfsy
Building a nameTx:              MINTX_CHAINID=six
                              MINTX_NODE_ADDR=http://toad:46657/
                                 MINTX_PUBKEY="removed"
                              MINTX_SIGN_ADDR=http://keys:4767
                                       amount=10000
                                         data=Qmc1CiNDurQU6UQ9sUyuKbdFQvW2avpcCgnDTax5K1rfsy
                                         name=contract.sol
Success, nameTx created:                      NameTx{TxInput{AF34D72EE9FE8E6FB...........
contract.sol: Qmc1CiNDurQU6UQ9sUyuKbdFQvW2avpcCgnDTax5K1rfsy}
Signing transaction...
Success updating the name registry
Caching hash now
Pinning hash to your local IPFS node
```

**Comment by zramsay** [comment] 2016-02-15 23:33
Hm. it should work even if those fields are left as is (it'll skip those failures - it's really a cheap load balancer). That it's hanging on `Pinning hash to your local IPFS node` tells me it doesn't make it past [here](https://github.com/eris-ltd/toadserver/blob/master/post_and_get.go#L97-L105), which indicates an issue with the local IPFS node. As previously mentioned, this is a common hangup for which we don't really have a solution other than pinging it till it works. 

There isn't yet documentation for `TOADSERVER_IPFS_NODES`. The idea is to pass in an array and IPs addrs that are/will be running an instance of the toadserver at port `11113` (these nodes need not have the key or link to a chain - only ipfs). Then, when a file is added from the master host, it'll pin/cache to each one of those ipfs nodes (through the toadserver). There's no authentication whatsoever though I'll get there eventually.

**Comment by zramsay** [comment] 2016-02-15 23:35
`other than pinging it till it works` => indeed, we had to refactor some of the `eris-cli` tests that used ipfs to instead use a fake ipfs server, since those failures were a burden.

**Comment by zramsay** [comment] 2016-02-16 03:01
Ok so it looks like we've been having similar issues unrelated to the above comments. Things appear to have cleared up with the most recent image build. To update: if ipfs already running: `eris services update ipfs`. To update all eris stock images to latest, re-run `eris init` or `eris update --pull-images` though the latter might be a tad buggy. Of course, you can always `docker pull quay.io/eris/ipfs:latest`.

**Comment by kootenpv** [comment] 2016-02-17 21:11
Things seem to be happening, but in the end not. From a fresh try (after updating ipfs/toadserver) :

```
eris services stop toadserver
eris services start toadserver --chain six

# server now runs

curl http://localhost:11113/postfile/a.json
curl http://localhost:11113/getfile/a.json
curl: (52) Empty reply from server

# server now not running anymore

Receiving GET request
Looking for filename:                         a.json
Post http://toad:46657/get_name: dial tcp: lookup toad on 168.63.129.16:53: no such host
```

**Comment by zramsay** [comment] 2016-02-17 22:04
Looks like it can't find the chain to lookup the entry. Is the chain running at `168.63.129.16` ? Can you confirm the file was added via post?

**Comment by kootenpv** [comment] 2016-02-17 22:45
Perhaps my IP changed as it is hosted on Azure? I'll use `eris init`, try again, and post the result.

**Comment by zramsay** [comment] 2016-03-05 20:13
CI testing recently added & going green. see `tests/test.sh`. re-open if this is still an issue

**Closed by zramsay** 2016-03-05 20:13 UTC
